---
kind: pipeline
name: amd64
platform:
  os: linux
  arch: amd64
steps:
- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    auto_tag: true
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
    repo: "quay.io/kontena/pharos-helm-worker-amd64"
    registry: quay.io
    tag: "${DRONE_TAG}"
    build_args:
    - ARCH=amd64
  when:
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
---
kind: pipeline
name: arm64
platform:
  os: linux
  arch: arm64
steps:
- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    auto_tag: true
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
    repo: "quay.io/kontena/pharos-helm-worker-arm64"
    registry: quay.io
    tag: "${DRONE_TAG}"
    build_args:
    - ARCH=arm64
  when:
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
